### PR TITLE
React game

### PR DESCRIPTION
**Pull request by Puckoland**

### CODE REVIEW

**Review by xbaran4 — COMMENTED** [review]
we dont need those .png (sword, crowns...) right? and I can create svg for arrows if you we want

**Review by xbaran4 — APPROVED** [review]

**Comment by Puckoland** [comment]
> We dont need those .png (sword, crowns...) right? and I can create svg for arrows if you we want.
> Do you want to keep the foldres with resources in src?
> 

Those are just temporary ... I will replace them with yours svg shortly.
I think it would be good to have some arrow, so we can show premoves to user. (But maybe in different color?)

**Comment by danieltimko** [comment]
Prečo si píšete po anglicky?

**Comment by Puckoland** [comment]
> Prečo si píšete po anglicky?

Because it is good practice to do so. And now when we are public repository... I think we should write in English...

**Pull request merged**
